### ISSUE TITLE
Player death issue

### ISSUE THREAD

**Issue by CLiu13** [AndreTheGamer/SurvivalGame#44]
Undefined variable: $inv issue when a player dies (was an issue in old version too).

**Comment by xZeroMCPE** [comment]
I thought i fixed it, Anyway i'm looking into it now. And an update should release saturday.

**Comment by CLiu13** [comment]
Alright, thank you very much!

**Comment by dries-c** [comment]
i have found the same bug

**Comment by xZeroMCPE** [comment]
xD I thought it was fixed, Anyway it's being fix now...

**Comment by dries-c** [comment]
fixed

**Comment by CLiu13** [comment]
Still not fixed.. new error!

Error: Call to a member function getInventory() on array
File: /plugins/SurvivalGame.phar/src/Andre/SurvivalGame/Main
Line: 1185
Type: E_ERROR

**Comment by xZeroMCPE** [comment]
Working on fixing it, as of today don't worry it"ll be fixed.

**Comment by CLiu13** [comment]
:+1:

**Comment by xZeroMCPE** [comment]
Hi, try BukkitPE. SurvivalGames works best with it.. It's a stable software that has a whole new API changes better then pocketmine. 

It supports
- Potions
- Mobs AI
- XP
- Enchanted
- And more+
  Visit: https://github.com/BukkitPE/BukkitPE

**Comment by xZeroMCPE** [comment]
Hi, this bug has been fixed. Please check out the main SurvivalGame github page for more info and links leading to download link for the new release.

INFO: **As of today, Me and my team has been working on a custom version of pocketmine which is called: BukkitPE it's more stable and supports Mobs,Weather,Nether,Potions,XP,Enchanted.. and more. And survivalgame has some features that only works with BukkitPE**

More info can be found here:

Website: BukkitPE.net
GitHub: www.github.com/bukkitpe/bukkitpe

**Download plugins for BukkitPE by going forums.bukkitpe.net then click plugins  (SurvivalGame has been added there too and it supports many more feature) and SurvivalGame has some features that only works using BukkitPE. What are  you waiting for?? Switch now**

Thanks, We've hope that you switch to BukkitPE

~ Andre
